CART/urls.py
# urls.py

from django.urls import path
from .views import *

urlpatterns = [
    # Other URL patterns...
    # path('add_to_cart/<int:id>/', add_to_cart, name='some_view'),
    path('add_to_cart/<str:product_variant_id>/', add_variant_to_cart, name='add_to_cart'),
    path('check_variant_in_cart/<str:product_variant_id>/', check_variant_in_cart, name='check_variant_in_cart'),
    path('decrement_cart_item/<str:product_variant_id>/', decrement_cart_item, name='decrement_cart_item'),
    path('clear_cart/', clear_cart, name='clear_cart'),
    path('get_cart_count/', get_cart_count, name='get_cart_count'),
    path('cart/remove-item/<str:product_variant_id>/', clear_cart_item, name='clear_cart_item'),

]

qtips/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from Authenticationapp import views
from Authenticationapp import views
from django.conf.urls import handler400,handler500,handler404,handler403
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('logout/',views.logout_req,name="logout" ),
    path('',include('CART.urls')),
    path('',include('Ecommerceapp.urls')),
    #  path('',include('wishlist.urls')),
    path('auth/',include('Authenticationapp.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#Django Administration apperarence edit
admin.site.site_header = "QTipstore Administration"
admin.site.site_title = "QTipstore Admin Portal"
admin.site.index_title = "Welcome to QTipstore Researcher Portal"

Ecommerceapp/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db.models.signals import pre_save
import uuid
import hashlib
from django.utils.crypto import get_random_string
from django.utils.html import format_html
from django.urls import reverse
from django.utils.safestring import mark_safe
from autoslug import AutoSlugField

from django.dispatch import receiver
from django.db.models.signals import post_save
from django.contrib.contenttypes.fields import GenericRelation
from taggit.managers import TaggableManager


class Main_categorie(models.Model):
    name = models.CharField(null=True,max_length=200)
    image = models.ImageField(upload_to='Main_category_images',null=True,blank=True)
    slug = models.SlugField(max_length=255,null=True, unique=True,blank=True)


    def __str__(self):
        return self.name

class Categorie(models.Model):
    main_category = models.ForeignKey(Main_categorie,on_delete=models.CASCADE)
    name = models.CharField(null=True,max_length=200)
    image = models.ImageField(upload_to='Subcategory_images',null=True,blank=True)
    slug = models.SlugField(max_length=255, unique=True,null=True,blank=True)
    popular=models.BooleanField(default=False)


    def __str__(self):
        return self.name + " -> " + self.main_category.name

class Sub_categorie(models.Model):
    category = models.ForeignKey(Categorie,on_delete=models.CASCADE)
    name = models.CharField(null=True,max_length=200)
    slug = models.SlugField(max_length=255, unique=True,null=True,blank=True)


    def __str__(self):
        return self.name +"->"+self.category.name+"->"+ self.category.main_category.name
    
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    address = models.TextField()
    gender = models.CharField(max_length=10, choices=[('male', 'Male'), ('female', 'Female')])
    
    def _str_(self):
        return self.full_name

class Coupon(models.Model):
    code = models.CharField(null=True,max_length=200)
    discount = models.IntegerField(null=True,)

    def __str__(self):
        return self.code

class Tag(models.Model):
    name = models.CharField(null=True,max_length=200)

    def __str__(self):
        return self.name




class Color(models.Model):
    code = models.CharField(null=True,max_length=100)
    name = models.CharField(max_length=200)


    def color_tag(self):
        if self.code is not None:
            return mark_safe('<p style="background-color: {}">Color </p>'.format(self.code))
        else:
            return ""

    def __str__(self):
        return self.name

class Size(models.Model):
    name = models.CharField(null=True,max_length=200)
    code = models.CharField(max_length=10, blank=True, null=True)

    def __str__(self):
        return self.name




class Partners(models.Model):
    name = models.CharField(null=True,max_length=100)
    image = models.ImageField(null=True,)

    def __str__(self):
        return self.name


class  Brands(models.Model):
    Brand_name=models.CharField(null=True,max_length=100)
    image = models.ImageField(upload_to='Brand_images',null=True,blank=True)


    def __str__(self):
        return self.Brand_name




class Discount_deal(models.Model):
    name = models.CharField(null=True,max_length=200)
    Discount = models.FloatField(default=0)
    slug = models.SlugField(unique=True, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)


    def __str__(self):
        return f"{self.id} {self.name}"

class Sliders(models.Model):


    image = models.ImageField(null=True,upload_to='slider_imgs')
    Discount_deal = models.ForeignKey(Discount_deal,on_delete=models.CASCADE)
    Sale = models.IntegerField(null=True,)
    Discount = models.IntegerField(null=True)
    Description_1 = models.CharField(null=True,max_length=100)
    Description_2 = models.CharField(null=True,max_length=200)
    Link = models.CharField(null=True,max_length=2000)

    def __str__(self):
        return self.Description_1

class Header_Icons(models.Model):
    Category = models.ForeignKey(Categorie,on_delete=models.CASCADE,null=True)
    # name = models.CharField(max_length=200,null=True)
    Icon = models.CharField(max_length=200,null=True)

    def __str__(self):
        return self.Category.name


class Section(models.Model):
    name = models.CharField(null=True,max_length=150)
    contains_products = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Moving_text(models.Model):
    text = models.CharField(null=True,max_length=300)
    section = models.ForeignKey(Section,on_delete=models.CASCADE,null=True,blank=True)
    date=models.DateTimeField(null=True,default=timezone.now)

    def __str__(self):
        return self.text

class Banners(models.Model):


    image = models.ImageField(null=True,upload_to='sm_banners')
    Key_point_2 = models.CharField(null=True,max_length=100)
    Discount_deal = models.ForeignKey(Discount_deal, on_delete=models.CASCADE,null=True,)
    Key_point_1 = models.CharField(null=True,max_length=200)
    Discount = models.IntegerField(null=True,blank=True)
    Link = models.CharField(max_length=2000,null=True,blank=True)
    section = models.ForeignKey(Section,null=True,on_delete=models.CASCADE)
    # category = models.ForeignKey(Categorie,null=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.Key_point_2




class Product(models.Model):
    slug = models.SlugField(default='', max_length=500, null=True, blank=True)
    name = models.CharField(null=True, max_length=500)
    # image = models.ImageField(null=True, upload_to='Product_images')
    def get_upload_path(instance, filename):
        # Generate a folder name based on the product name
        folder_name = slugify(instance.name)[:30]

        # Define the upload path using the folder_name
        upload_path = f"Product_images/{folder_name}"

        # Return the final upload path
        return f"{upload_path}/{filename}"
    image = models.ImageField(blank=True,null=True,upload_to=get_upload_path)
    total_quantity = models.IntegerField(null=True,blank=True)
    Availability = models.IntegerField(null=True,blank=True)
    price = models.FloatField(null=True,blank=True)
    Discount = models.IntegerField(null=True,blank=True)
    tax = models.FloatField(null=True, blank=True)
    packing_cost = models.FloatField(null=True, blank=True)
    Product_info = RichTextField(null=True,blank=True)
    model_name = models.CharField(null=True, max_length=120,blank=True)
    Category = models.ForeignKey('Categorie', null=True, on_delete=models.CASCADE,blank=True)
    Deals = models.ForeignKey('Discount_deal', null=True, on_delete=models.CASCADE,blank=True)
    Sub_category = models.ForeignKey('Sub_categorie', on_delete=models.CASCADE, null=True, blank=True)
    Tags = models.ForeignKey('Tag', null=True, blank=True, on_delete=models.CASCADE)
    Description = RichTextField(null=True,blank=True)
    Section = models.ForeignKey('Section', null=True, on_delete=models.DO_NOTHING,blank=True)
    brand = models.ForeignKey('Brands', on_delete=models.CASCADE, null=True, blank=True)
    original_price = models.FloatField(null=True, blank=True)
    cod = models.BooleanField(default=False,null=True)
    seller = models.CharField(max_length=255)
    seller_description = models.CharField(max_length=255, null=True, blank=True)
    seller_since = models.DateField(null=True, blank=True)

    rating = models.FloatField(default=0.0,null=True,blank=True)
    color=models.BooleanField(default=False,null=True)
    size=models.BooleanField(default=False,null=True)

    def update_average_rating(self):
        # Calculate and update the average rating for the product using Comment model
        ratings = Comment.objects.filter(product=self)
        if ratings.exists():
            average_rating = ratings.aggregate(models.Avg('numeric_rating'))['numeric_rating__avg']
            self.rating = round(average_rating, 1)  # Round to one decimal place
        else:
            self.rating = 0.0

        self.save()

    def variants(self):
        # Return the variants related to this product
        return Variants.objects.filter(product=self)

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url) if self.image else '')

    image_tag.short_description = 'Image'


    def quantity_sold(self):
        return self.total_quantity - self.Availability

    def __str__(self):
        return f"{self.id} {self.name}"


    def save(self, *args, **kwargs):
        # Your existing save logic
        if not self.slug:
            self.slug = self.generate_custom_id()
        super().save(*args, **kwargs)

    def generate_custom_id(self):
        from django.utils.crypto import get_random_string
        current_time = timezone.now()
        timestamp_milliseconds = int(current_time.timestamp() * 1000)

        # Modify this part according to your needs
        sliced_name = self.name.split()[0]
        return f"qtip{slugify(sliced_name)}pd{timestamp_milliseconds}_{get_random_string(5)}"
    def get_absolute_url(self):
        return reverse("product_detail", kwargs={'slug': self.slug})

    def custom_id(self):
        return f"Custom ID: {self.slug}"

    def get_average_rating(self):
        # Calculate the average rating for the product using Comment model
        ratings = Comment.objects.filter(product=self)
        if ratings.exists():
            average_rating = ratings.aggregate(models.Avg('numeric_rating'))['numeric_rating__avg']

templates/includes/cta.html
<section class="cta-area d-ldark-bg pt-55 pb-10">
    <div class="container">
        <div class="row">
            <div class="col-lg-4 col-md-6">
                <div class="cta-item cta-item-d mb-30">
                    <h5 class="cta-title">Follow Us</h5>
                    <p>We make consolidating, marketing and tracking your social media website easy.</p>
                    <div class="cta-social">
                        <div class="social-icon">
                            <a href="#" class="facebook"><i class="fab fa-facebook-f"></i></a>
                            <a href="#" class="twitter"><i class="fab fa-twitter"></i></a>
                            <a href="#" class="youtube"><i class="fab fa-youtube"></i></a>
                            <a href="#" class="linkedin"><i class="fab fa-linkedin-in"></i></a>
                            <a href="#" class="rss"><i class="fas fa-rss"></i></a>
                            <a href="#" class="dribbble"><i class="fab fa-dribbble"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="cta-item mb-30">
                    <h5 class="cta-title">Sign Up To Newsletter</h5>
                    <p>Join 60.000+ subscribers and get a new discount coupon  on every Saturday.</p>
                    <div class="subscribe__form">
                        <form action="#">
                            <input type="email" placeholder="Enter your email here...">
                            <button>subscribe</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 col-md-6">
                <div class="cta-item mb-30">
                    <h5 class="cta-title">Download App</h5>
                    <p>QTipstore App is now available on App Store & Google Play. Get it now.</p>
                    <div class="cta-apps">
                        <div class="apps-store">
                            <a href="#"><img src="{% static 'assets/img/brand/app_ios.png' %}" alt=""></a>
                            <a href="#"><img src="{% static 'assets/img/brand/app_android.png' %}" alt=""></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

templates/includes/features.html
<section class="features__area pt-20">
    <div class="container">
        <div class="row row-cols-xxl-4 row-cols-xl-4 row-cols-lg-4 row-cols-md-2 row-cols-sm-2 row-cols-1 gx-0">
            <div class="col">
                <div class="features__item d-flex white-bg">
                    <div class="features__icon mr-20">
                        <i class="fal fa-truck"></i>
                    </div>
                    <div class="features__content">
                        <h6>FREE DELIVERY</h6>
                        <p>For all orders over $120</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="features__item d-flex white-bg">
                    <div class="features__icon mr-20">
                        <i class="fal fa-money-check"></i>
                    </div>
                    <div class="features__content">
                        <h6>SAFE PAYMENT</h6>
                        <p>100% secure payment</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="features__item d-flex white-bg">
                    <div class="features__icon mr-20">
                        <i class="fal fa-comments-alt"></i>
                    </div>
                    <div class="features__content">
                        <h6>24/7 HELP CENTER</h6>
                        <p>Delicated 24/7 support</p>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="features__item features__item-last d-flex white-bg">
                    <div class="features__icon mr-20">
                        <i class="fad fa-user-headset"></i>
                    </div>
                    <div class="features__content">
                        <h6>FRIENDLY SERVICES</h6>
                        <p>30 day satisfaction guarantee</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

templates/includes/footer.html
 <!-- footer-start -->
 {% load static %}
    <footer>
        <div class="fotter-area d-ddark-bg">
            <div class="footer__top pt-60 pb-10">
                <div class="container 0">
                    {% comment %} <div class="row">
                        <div class="col-xxl-2 col-xl-3 col-lg-3 col-md-4 col-sm-6" style="display: flex;width:inherit;flex-wrap:wrap;gap:1rem">
                            {% for i in main_category %}
                            <div class="footer__widget footer-col-2">
                                
                                <div class="footer__widget-title">
                                    <h4>{{i.name}}</h4>
                                </div>
                                <div class="footer__widget-content">
                                    <div class="footer__link footer__link-2">
                                        <ul>
                                            {% for j in i.categorie_set.all %}
                                            <li><a href="/sub_cats/?categories={{j.id}}">{{j.name}}</a></li>
                                            
                                {% endfor %}
                                        
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div> {% endcomment %}
                    <div class="row">
                        <div class="col-xxl-3 col-xl-4 col-lg-5 col-md-8">
                            <div class="footer__widget">
                                <div class="footer__widget-title mb-20">
                                    <h4>About The Store</h4>
                                </div>
                                <div class="footer__widget-content">
                                    <p class="footer-text mb-25">Our mission statement is to provide the absolute best customer experience available in the Electronic industry without exception.</p>
                                    <div class="footer__hotline d-flex align-items-center mb-10">
                                        <div class="icon icon-2 mr-15">
                                            <i class="fal fa-headset"></i>
                                        </div>
                                        
                                    </div>
                                    <div class="footer__info">
                                        <ul>
                                            <li>
                                                <span>Add:  <a target="_blank" href="https://goo.gl/maps/c82DDZ8ALvL878Bv8">QTipstore Pvt. Ltd, Dishuknagar</a></span>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xxl-2 col-xl-3 col-lg-3 col-md-4 col-sm-6">
                            <div class="footer__widget footer-col-2">
                                <div class="footer__widget-title">
                                    <h4>My Account</h4>
                                </div>
                                <div class="footer__widget-content">
                                    <div class="footer__link footer__link-2">
                                        <ul>
                                            <li><a href="/checkout/">Checkout</a></li>
                                            <li><a href="/cart/cart-detail/">Shopping Cart</a></li>
                                            
                                            <!-- <li><a href="#">Terms &amp; Conditions &amp;</a></li> -->
                                        
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xxl-2 col-xl-3 col-lg-3 col-md-4 col-sm-6">
                            <div class="footer__widget footer-col-2">
                                <div class="footer__widget-title">
                                    <h4>Customer Care</h4>
                                </div>
                                <div class="footer__widget-content">
                                    <div class="footer__link footer__link-2">
                                        <ul>
                                            <li><a href="/auth/signup">New Customer</a></li>
                                            <li><a href="/cancellation/">cancellation</a></li>
                                            <!-- <li><a href="#">How to use Account</a></li>
                                            <li><a href="#">Placing an Order</a></li>
                                            <li><a href="#">Payment Methods</a></li>
                                            <li><a href="#">Delivery &amp; Dispatch</a></li>
                                            <li><a href="#">Problems with Order</a></li> -->
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-xxl-2 col-xl-2 col-lg-3 col-md-4 col-sm-6">
                            <div class="footer__widget footer-col-2">
                                <div class="footer__widget-title">
                                    <h4>Customer Service</h4>
                                </div>
                                <div class="footer__widget-content">
                                    <div class="footer__link footer__link-2">
                                        <ul>
                                            <li><a href="/contact/">Contact Us</a></li>
                                            <li><a href="/privacy_policy/">Policies &amp; Rules</a></li>
                                            <li><a href="/shipping_policy/">Shipping Policy</a></li>
                                            <li><a href="/payment_policy/">Payment Policy</a></li>
                                            <li><a href="/image_courtesy">Image Courtesy</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
            </div>
            <div class="footer__bottom-2">
                <div class="container 0">
                    <div class="footer__bottom-content footer__bottom-content-2 pt-50 pb-50">
                        <div class="row">
                            <div class="col-xl-12">
                                <div class="footer__links footer__links-d text-center mb-25">
                                    <p>
                                        <a href="/about/">About Us</a>
                                        <a href="/return_refund/">Delivery & Return</a>
                                        <a href="/privacy_policy/">Privacy Policy</a>
                                        <!-- <a href="#">Help</a> -->
                                        <!-- <a href="#">Order Tracking</a> -->
                                        <a href="/contact/">Contact Us</a>
                                        <!-- <a href="#">FAQs </a> -->
                                    </p>
                                </div>
                                <div class="payment-image text-center mb-25">
                                    <a href="#"><img src="{% static 'assets/img/payment/payment.png' %}" alt=""></a>
                                </div>
                                <div class="copy-right-area copy-right-area-2 text-center">
                                    <p>Copyright © <span>QTipstore.</span> All Rights Reserved. Powered by <a href="#"><span class="main-color">QTipstore.</span></a></p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- footer-end -->